<?php
if(!isset($pdo))require dirname(__DIR__).'/bootstrap.php';
$uid=(int)$_SERVER['GH_UPLOAD_USER_ID'];$file=$_SERVER['GH_UPLOAD_FILE'];$name=basename($_SERVER['GH_UPLOAD_NAME']);
if(!is_file($file)||filesize($file)>8000000)throw new RuntimeException('Invalid or oversized CSV.');
$hash=hash_file('sha256',$file);$dupe=$pdo->prepare('SELECT id FROM gh_walk_tracks WHERE user_id=? AND file_hash=?');$dupe->execute(array($uid,$hash));if($dupe->fetch()){$GLOBALS['GH_DUPLICATE']=true;return;}
$fh=fopen($file,'r');$header=fgetcsv($fh);if(!$header)throw new RuntimeException('CSV header missing.');$keys=array_map('strtolower',$header);$latI=array_search('latitude',$keys);$lonI=array_search('longitude',$keys);$timeI=array_search('timestamp_utc',$keys);$accI=array_search('accuracy_m',$keys);$providerI=array_search('provider',$keys);if($latI===false||$lonI===false)throw new RuntimeException('CSV must contain latitude and longitude.');
$rows=array();$first=null;$last=null;while(($r=fgetcsv($fh))!==false&&count($rows)<100000){$lat=(float)$r[$latI];$lon=(float)$r[$lonI];if($lat < -90||$lat > 90||$lon < -180||$lon > 180)continue;$stamp=($timeI!==false&&!empty($r[$timeI]))?date('Y-m-d H:i:s',strtotime($r[$timeI])):null;if($stamp){if(!$first)$first=$stamp;$last=$stamp;}$rows[]=array($stamp,$lat,$lon,$accI!==false?(float)$r[$accI]:null,$providerI!==false?substr($r[$providerI],0,30):null);}fclose($fh);if(count($rows)<2)throw new RuntimeException('Walk needs at least two valid GPS points.');
$city=$pdo->prepare('SELECT id FROM gh_cities WHERE enabled=1 AND ? BETWEEN min_lat AND max_lat AND ? BETWEEN min_lon AND max_lon ORDER BY id LIMIT 1');$city->execute(array($rows[0][1],$rows[0][2]));$cityId=$city->fetchColumn();
$pdo->beginTransaction();try{$add=$pdo->prepare('INSERT INTO gh_walk_tracks(user_id,city_id,title,original_filename,file_hash,point_count,started_at,ended_at) VALUES(?,?,?,?,?,?,?,?)');$add->execute(array($uid,$cityId,'Walk '.date('M j, Y g:i A'),$name,$hash,count($rows),$first,$last));$track=(int)$pdo->lastInsertId();$point=$pdo->prepare('INSERT INTO gh_walk_points(track_id,sequence_no,recorded_at,latitude,longitude,accuracy_m,provider) VALUES(?,?,?,?,?,?,?)');foreach($rows as $i=>$r)$point->execute(array($track,$i,$r[0],$r[1],$r[2],$r[3],$r[4]));$pdo->commit();$GLOBALS['GH_TRACK_ID']=$track;require_once __DIR__.'/map_match.php';gh_map_match_track($pdo,$track);}catch(Exception $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
