plugins {
    id 'com.android.application'
}

android {
    namespace 'com.graffitihunter.demo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.graffitihunter.demo'
        minSdk 26
        targetSdk 36
        versionCode 34
        versionName '0.5.7'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    packaging {
        jniLibs { useLegacyPackaging true }
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.media3:media3-exoplayer:1.10.1'
    implementation 'androidx.media3:media3-exoplayer-rtsp:1.10.1'
    implementation files('libs/ijkplayer-java-0.8.8.aar')
    implementation files('libs/ijkplayer-arm64-0.8.8.aar')
}
